### ISSUE TITLE
Instancing Edges on Suzanne "IndexError: list index out of range"

### ISSUE THREAD

**Issue by MxAshUp** [aconz2/blender-instancing-addon#1]
**How to Reproduce**:
1) Start with an empty blend file in 2.82a or 2.82.
2) Add a suzanne model to the scene.
3) Run instancing++
4) Select "edges"

This error appears:
```
Traceback (most recent call last):
  File "/home/dustin/.config/blender/2.82/scripts/addons/instancing.py", line 90, in execute
    k = edge_normal(e)
  File "/home/dustin/.config/blender/2.82/scripts/addons/instancing.py", line 36, in edge_normal
    return (faces[0].normal + faces[1].normal) / 2
IndexError: list index out of range
```

The suzanne model works fine with vertices and faces, however.

Hope this helps!

**Comment by aconz2** [comment]
Thanks for the issue.
It is due to edges which don't join 2 faces.

Fixed [here](https://github.com/aconz2/blender-instancing-addon/commit/6997bf509addd741aa49c6644492e8426ae71ab5) by skipping edges which don't join 2 faces and issuing a warning to display the count of skipped edges.

Suzanne for instance has 42 such edges out of 1005. It takes a few seconds on my machine to add all the instances but works fine after that.
[Ice monkey?](https://aconz2-public.s3.amazonaws.com/9cdd064e-d50e-4900-ad8e-8b0b4b94a4f3/suzanne-ice.jpg)
